# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

obj2Cpp <- function(uR, xij, xj, weightsR, band) {
    .Call('_ClusPred_obj2Cpp', PACKAGE = 'ClusPred', uR, xij, xj, weightsR, band)
}

obj3Cpp <- function(uR, xj, weightsR, band) {
    .Call('_ClusPred_obj3Cpp', PACKAGE = 'ClusPred', uR, xj, weightsR, band)
}

